query Users {
  users {
    email
    id
  }
}

mutation SignUp($data: NewUserInput!) {
  createUser(data: $data) {
    email
    id
    pseudo
    role
  }
}

mutation SignIn($data: SigninInput!) {
  signin(data: $data)
}

mutation Logout {
  logout
}

query GetUserProfile {
  getUserProfile {
    email
    id
    pseudo
    role
  }
}
