services:
  db:
    image: postgres:15-alpine
    stop_grace_period: 0s
    environment:
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 2s
      timeout: 2s
      retries: 10
    ports:
      - 5432:5432

  backend:
    build: backend
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src
    stop_grace_period: 0s
    environment:
      - DB_HOST=db
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      db:
        condition: service_healthy

  frontend:
    stop_grace_period: 0s
    build: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
